#!/usr/bin/env bash
# install nginx

# Update package lists and install nginx
apt-get -y update
apt-get -y install nginx

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

# Add "Hello World!" to the default index.html
sudo echo "Hello World!" > /var/www/html/index.html

service nginx start
