#!/bin/bash
# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Write "Hello World!" to the default Nginx HTML file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Add a redirection rule to Nginx configuration
sudo sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# Start Nginx service
sudo service nginx start
