#!/usr/bin/env bash

# Install nginx on web server
sudo apt-get update
sudo apt-get -y install nginx

# Start nginx service
sudo service nginx start

# Add a custom 404 page
sudo bash -c 'echo "Ceci n'\''est pas une page" > /usr/share/nginx/html/custom_404.html'

# Configure Nginx to use the custom 404 page for 404 errors
sudo sed -i 's/#error_page 404 \/404.html;/error_page 404 \/custom_404.html;/' /etc/nginx/sites-available/default

# Restart nginx service to apply changes
sudo service nginx restart

