#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# redirects to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By \$hostname;
    }
    error_page 404 /404.html;

    location = /404.html {
        root /var/www/html;
        internal;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html

sudo service nginx restart
