#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo pt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend Randommall.tech_backend

backend Randommall.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 368897-web-01 18.206.233.209:80 check
    server 368897-web-02 34.232.65.160:80 check
EOT

sudo service haproxy restart
