#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
sudo apt-get purge haproxy
sudo apt-get update

sudo apt-get install -y haproxy
# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web1 100.26.225.15:80 check
    server web2 54.237.106.87:80 check
EOF
sudo service haproxy restart
