#!/usr/bin/env bash
# Display username, user id, and home directory path from /etc/passwd

cut -d ':' -f 1,3,6 < /etc/passwd | while IFS=: read -r username userid homedir; do
	echo "$username:$userid:$homedir"
done
