#!/usr/bin/env bash
# displays Best School 10 times.

file="/etc/passwd"

while IFS=':' read -r username password uid gid full_name home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $full_name"
done < "$file"