#!/usr/bin/env bash
# lists files in the current directory and extracts text after the first dash

for file in *; do
	if [[ $file != .* ]]; then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
