#!/usr/bin/env bash
# configure HAproxy on lb-01 server.

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to IdentityFile
ssh-add ~/.ssh/school

# Username and IP Address 
ssh ubuntu@54.237.81.77
